### ISSUE TITLE
Error creates and include_tasks

### ISSUE THREAD

**Issue by cstegm** [chrnie/ansible-role-icinga2#7]
Hi @chrnie 

there is an error in the include of the pki.yml:

```
- name: Manage Certificates
  include_tasks: "pki.yml"
  creates: "/var/lib/icinga2/certs/{{ icinga2_nodename }}.crt"
  when: inventory_hostname != icinga2_ca_host
  tags:
    - install
    - update
```

```
FAILED! => {"reason": "'creates' is not a valid attribute for a TaskInclude\n\nThe error appears to have been in '/data/icinga2-vagrant-ansible/roles/chrnie.icinga2/tasks/config-master.yml': line 38, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Manage Certificates\n  ^ here\n\nThis error can be suppressed as a warning using the \"invalid_task_attribute_failed\" configuration"}
```

can you fix this please? it seems that creates is not supported anymore in this case.
